spring.application.name=datavalidation
# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://172.21.202.89/bookstore
spring.datasource.username=root
spring.datasource.password=7GL19xOWDrUDIaUqk5BYTAnj

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true